version: '3.9'

services:
  app:
    image: ghcr.io/duopus/rundown-editor:latest
    container_name: duopus-rundown-editor
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3010
      - DATA_DIR=/app/data
      - NODE_ENV=production
    ports:
      - '3010:3010'
    volumes:
      - ./data:/app/data
    restart: unless-stopped
