name: Dependencies Check

on:
  push:
    branches:
      - '**'
    tags:
      - 'v**'

permissions:
  contents: read

jobs:
  validate-prod-dependencies-packages:
    name: Validate Package production dependencies
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
      - name: Prepare Environment
        run: |
          corepack enable
          yarn install
        env:
          CI: true
      - name: Validate production dependencies
        run: |
          if scripts/ci-should-skip-audit.sh; then
            echo "Skipping audit"
          else
            yarn validate:dependencies
          fi
        env:
          CI: true
          GITHUB_TOKEN: ${{ github.token }}

  validate-all-dependencies-packages:
    name: Validate all Package dependencies
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
      - name: Prepare Environment
        run: |
          corepack enable
          yarn install
        env:
          CI: true
      - name: Validate production dependencies
        run: |
          if scripts/ci-should-skip-audit.sh; then
            echo "Skipping audit"
          else
            yarn validate:dependencies
          fi
        env:
          CI: true
          GITHUB_TOKEN: ${{ github.token }}
      - name: Validate dev dependencies
        run: |
          if scripts/ci-should-skip-audit.sh; then
            echo "Skipping audit"
          else
            yarn validate:dev-dependencies
          fi
        env:
          CI: true
          GITHUB_TOKEN: ${{ github.token }}
